version: "3.9"
services:
  dex:
    image: dexidp/dex
    ports: 
      - 5556:5556
    volumes:
      - ./dex:/etc/dex
    command: dex serve /etc/dex/config.yaml
    networks:
      - dex
      - front-end
  front-end:
    depends_on:
      - dex
    build: ./front-end
    ports:
      - 3000:3000
    networks:
      - front-end
  back-end:
    build: ./back-end
    ports:
      - 3001:3001
    networks:
      - back-end
      - front-end

networks:
  back-end: 
  front-end: 
  dex: 
